name: server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  dart_dotenv: ^1.0.1
  dotenv: ^4.2.0
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  firebase_admin: ^0.2.1
  firebase_admin_firestore: ^0.2.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
